### ISSUE TITLE
Interaction overcounting in Ising model

### ISSUE THREAD

**Issue by swertz** [DPotoyan/Statmech4ChemBio#1]
Hello,

I don't understand why you divide by 4 here: https://github.com/DPotoyan/Statmech4ChemBio/blob/master/6_ising/src/basic_Ising2d.py#L58

Isn't the overcounting factor 2 rather than 4? I think every interaction only appears twice in the loop...

Cheers!

**Comment by DPotoyan** [comment]
Hello, sorry for responding late to this. Each spin has four neighbors, and the iteration is over every spin. Say you counted interactions with neighbors of spin (i,j). But then you overcount by including each neighbor spin and its four interactions.

**Comment by swertz** [comment]
Every spin has four neighbour, but a given pair of spins appears only twice in the loop...?

Say for spin (m,n), the interaction between (m-1,n) and (m,n) appears only twice in the loop: when (i,j)=(m-1,n) and when (i,j) = (m,n), so the overcounting factor is 2.
The interaction (m-1,n) <-> (m,n) does not appear for the 3 other direct neighbours of site (m,n): (m,n-1), (m,n+1), (m+1,n).

**Comment by DPotoyan** [comment]
You are correct. Each pairwise interaction is double-counted; I mentally divided total energy into per-spin contributions and included four. Will fix this. Thank you!

**Comment by swertz** [comment]
Thank you! :)
